// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResumePro.Jobs.Context;

#nullable disable

namespace ResumePro.Jobs.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ResumePro.Jobs.Entities.JobCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JobCategory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Jobs related to developing and maintaining software applications.",
                            Name = "Software Development"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Positions focused on promoting products and services.",
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Roles involved in selling products and services to customers.",
                            Name = "Sales"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Jobs related to recruiting",
                            Name = "Human Resources"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Positions focused on managing company finances and accounts.",
                            Name = "Finance"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Roles involved in supporting and assisting customers.",
                            Name = "Customer Service"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Jobs related to designing and building products or infrastructure.",
                            Name = "Engineering"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Positions focused on overseeing product development and strategy.",
                            Name = "Product Management"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Roles involved in managing day-to-day business operations.",
                            Name = "Operations"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Jobs related to legal compliance and providing legal advice.",
                            Name = "Legal"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Positions focused on administrative and clerical tasks.",
                            Name = "Administrative"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Jobs related to providing technical support and managing IT systems.",
                            Name = "IT Support"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Positions focused on innovating and developing new products.",
                            Name = "Research and Development"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Roles involved in teaching and educational administration.",
                            Name = "Education"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Jobs related to providing medical and healthcare services.",
                            Name = "Healthcare"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Positions focused on managing supply chain and distribution.",
                            Name = "Logistics"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Roles related to graphic design",
                            Name = "Creative"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Jobs focused on ensuring product or service quality.",
                            Name = "Quality Assurance"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Positions involved in the production of goods.",
                            Name = "Manufacturing"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Roles related to planning and overseeing projects.",
                            Name = "Project Management"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
