version: "3.9"

services:
  postgres:
    image: postgres:17-alpine
    container_name: resumepro_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=resumepro
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d resumepro"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  resumeprotest:
    build:
      context: "."  # assuming you run from the repo root
      dockerfile: src/ResumePro.IntegrationTests/DockerFile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ConnectionStrings__PostgreSQLConnection=Host=postgres;Port=5432;Database=resumepro;Username=postgres;Password=postgres
    command: >
      sh -c "dotnet test --collect:\"XPlat Code Coverage\" --results-directory:./TestResults --logger:console;verbosity=detailed &&
             /root/.dotnet/tools/reportgenerator -reports:\"./TestResults/**/coverage.cobertura.xml\" -targetdir:\"./CoverageReport\" -reporttypes:TextSummary &&
             cat ./CoverageReport/Summary.txt"

volumes:
  postgres_data:
