version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: resumepro_sql_db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    volumes:
      - sqlserver_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P \"YourStrong!Passw0rd\" -d master -Q \"SELECT 1\""]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 180s

  resumeprotest:
    build:
      # Since this file is located in src/ResumePro.IntegrationTests/,
      # we set the build context to two levels up (the repository root)
      context: "../../.."
      dockerfile: "src/ResumePro.IntegrationTests/DockerFile"
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=resumepro;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
    command: >
      sh -c "dotnet test --collect:\"XPlat Code Coverage\" --results-directory:./TestResults --logger \"console;verbosity=detailed\" &&
             /root/.dotnet/tools/reportgenerator -reports:\"./TestResults/**/coverage.cobertura.xml\" -targetdir:\"./CoverageReport\" -reporttypes:TextSummary &&
             cat ./CoverageReport/Summary.txt"

volumes:
  sqlserver_data:
