// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResumePro.Context;

#nullable disable

namespace ResumePro.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20240630203429_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ResumePro.Entities.Highlight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("Highlight");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            JobId = 1,
                            Order = 1,
                            Text = "Hello"
                        });
                });

            modelBuilder.Entity("ResumePro.Entities.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId");

                    b.ToTable("Job");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Company = "X Co",
                            Description = "Test Description",
                            Location = "Salt Lake City",
                            PersonaId = 1,
                            StartDate = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Architect"
                        },
                        new
                        {
                            Id = 2,
                            Company = "Y Co",
                            Description = "Test Description",
                            Location = "Salt Lake City",
                            PersonaId = 1,
                            StartDate = new DateTime(2002, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Architect"
                        });
                });

            modelBuilder.Entity("ResumePro.Entities.JobSkill", b =>
                {
                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<int>("ResumeId")
                        .HasColumnType("int");

                    b.HasKey("SkillId", "JobId");

                    b.HasIndex("ResumeId", "JobId");

                    b.HasIndex("ResumeId", "SkillId");

                    b.ToTable("JobSkill");

                    b.HasData(
                        new
                        {
                            SkillId = 1,
                            JobId = 1,
                            ResumeId = 1
                        },
                        new
                        {
                            SkillId = 1,
                            JobId = 2,
                            ResumeId = 1
                        });
                });

            modelBuilder.Entity("ResumePro.Entities.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GitHub")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkedIn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persona");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Salt Lake City",
                            Email = "rodmjay@gmail.com",
                            FirstName = "Rod",
                            GitHub = "https://www.linkedin.com/in/rodmjay",
                            LastName = "Johnson",
                            LinkedIn = "https://www.github.com/rodmjay",
                            PhoneNumber = "3853526026",
                            State = "UT"
                        });
                });

            modelBuilder.Entity("ResumePro.Entities.PersonaSkill", b =>
                {
                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("PersonaId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("PersonaSkill");

                    b.HasData(
                        new
                        {
                            PersonaId = 1,
                            SkillId = 1,
                            Rating = 10
                        });
                });

            modelBuilder.Entity("ResumePro.Entities.Reference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("Reference");
                });

            modelBuilder.Entity("ResumePro.Entities.Resume", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Resume");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Hello There",
                            PersonaId = 1,
                            ShortName = "C# Developer"
                        });
                });

            modelBuilder.Entity("ResumePro.Entities.ResumeJob", b =>
                {
                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<int>("ResumeId")
                        .HasColumnType("int");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("PersonaId", "ResumeId", "JobId");

                    b.HasIndex("JobId");

                    b.ToTable("ResumeJob");

                    b.HasData(
                        new
                        {
                            PersonaId = 1,
                            ResumeId = 1,
                            JobId = 1,
                            Order = 0
                        },
                        new
                        {
                            PersonaId = 1,
                            ResumeId = 1,
                            JobId = 2,
                            Order = 0
                        });
                });

            modelBuilder.Entity("ResumePro.Entities.ResumeSkill", b =>
                {
                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<int>("ResumeId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("PersonaId", "ResumeId", "SkillId");

                    b.HasIndex("PersonaId", "SkillId");

                    b.ToTable("ResumeSkill");

                    b.HasData(
                        new
                        {
                            PersonaId = 1,
                            ResumeId = 1,
                            SkillId = 1
                        });
                });

            modelBuilder.Entity("ResumePro.Entities.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Skill");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "C# Development"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Azure"
                        },
                        new
                        {
                            Id = 3,
                            Title = "Sql Server"
                        },
                        new
                        {
                            Id = 4,
                            Title = "Angular"
                        });
                });

            modelBuilder.Entity("ResumePro.Entities.Highlight", b =>
                {
                    b.HasOne("ResumePro.Entities.Job", "Job")
                        .WithMany("Highlighs")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("ResumePro.Entities.Job", b =>
                {
                    b.HasOne("ResumePro.Entities.Persona", "Persona")
                        .WithMany("Jobs")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("ResumePro.Entities.JobSkill", b =>
                {
                    b.HasOne("ResumePro.Entities.ResumeJob", "Job")
                        .WithMany("Skills")
                        .HasForeignKey("ResumeId", "JobId")
                        .HasPrincipalKey("ResumeId", "JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResumePro.Entities.ResumeSkill", "Skill")
                        .WithMany("Jobs")
                        .HasForeignKey("ResumeId", "SkillId")
                        .HasPrincipalKey("ResumeId", "SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("ResumePro.Entities.PersonaSkill", b =>
                {
                    b.HasOne("ResumePro.Entities.Persona", "Persona")
                        .WithMany("Skills")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResumePro.Entities.Skill", "Skill")
                        .WithMany("Personas")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("ResumePro.Entities.Reference", b =>
                {
                    b.HasOne("ResumePro.Entities.Job", "Job")
                        .WithMany("References")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("ResumePro.Entities.Resume", b =>
                {
                    b.HasOne("ResumePro.Entities.Persona", "Persona")
                        .WithMany("Resumes")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("ResumePro.Entities.ResumeJob", b =>
                {
                    b.HasOne("ResumePro.Entities.Job", "Job")
                        .WithMany("Resumes")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ResumePro.Entities.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResumePro.Entities.Resume", "Resume")
                        .WithMany("Jobs")
                        .HasForeignKey("PersonaId", "ResumeId")
                        .HasPrincipalKey("PersonaId", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Persona");

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("ResumePro.Entities.ResumeSkill", b =>
                {
                    b.HasOne("ResumePro.Entities.Resume", "Resume")
                        .WithMany("Skills")
                        .HasForeignKey("PersonaId", "ResumeId")
                        .HasPrincipalKey("PersonaId", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ResumePro.Entities.PersonaSkill", "Skill")
                        .WithMany("Resumes")
                        .HasForeignKey("PersonaId", "SkillId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Resume");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("ResumePro.Entities.Job", b =>
                {
                    b.Navigation("Highlighs");

                    b.Navigation("References");

                    b.Navigation("Resumes");
                });

            modelBuilder.Entity("ResumePro.Entities.Persona", b =>
                {
                    b.Navigation("Jobs");

                    b.Navigation("Resumes");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("ResumePro.Entities.PersonaSkill", b =>
                {
                    b.Navigation("Resumes");
                });

            modelBuilder.Entity("ResumePro.Entities.Resume", b =>
                {
                    b.Navigation("Jobs");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("ResumePro.Entities.ResumeJob", b =>
                {
                    b.Navigation("Skills");
                });

            modelBuilder.Entity("ResumePro.Entities.ResumeSkill", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("ResumePro.Entities.Skill", b =>
                {
                    b.Navigation("Personas");
                });
#pragma warning restore 612, 618
        }
    }
}
