// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResumePro.Context;

#nullable disable

namespace ResumePro.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20240630210503_InitialMigration9")]
    partial class InitialMigration9
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ResumePro.Entities.Highlight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("Highlight");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            JobId = 1,
                            Order = 1,
                            Text = "Managed the development and deployment mission-critical workflows related to software reliability"
                        },
                        new
                        {
                            Id = 2,
                            JobId = 1,
                            Order = 2,
                            Text = "Developed geneva logging library used by SRE department"
                        },
                        new
                        {
                            Id = 3,
                            JobId = 1,
                            Order = 3,
                            Text = "Developed dashboards to display real-time data of millions of records using Geneva"
                        },
                        new
                        {
                            Id = 4,
                            JobId = 1,
                            Order = 4,
                            Text = "Used bicep to deploy complex synapse workspaces across multiple environments"
                        },
                        new
                        {
                            Id = 5,
                            JobId = 1,
                            Order = 5,
                            Text = "Responsible for implementing integration testing patterns across multiple applications"
                        },
                        new
                        {
                            Id = 6,
                            JobId = 2,
                            Order = 1,
                            Text = ".NET leader (company-wide)"
                        },
                        new
                        {
                            Id = 7,
                            JobId = 2,
                            Order = 2,
                            Text = "Developed interview process for tech screenings and performed dozens of tech interviews"
                        },
                        new
                        {
                            Id = 8,
                            JobId = 2,
                            Order = 3,
                            Text = "Developed the common codebase used for all .NET projects"
                        },
                        new
                        {
                            Id = 9,
                            JobId = 2,
                            Order = 4,
                            Text = "Won award for highest producing developer in 2021"
                        });
                });

            modelBuilder.Entity("ResumePro.Entities.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId");

                    b.ToTable("Job");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Company = "InfoSys",
                            Description = "",
                            Location = "Salt Lake City",
                            PersonaId = 1,
                            StartDate = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Technical Architect"
                        },
                        new
                        {
                            Id = 2,
                            Company = "Solution Stream",
                            Description = "",
                            Location = "American Fork,UT",
                            PersonaId = 1,
                            StartDate = new DateTime(2002, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Sr. Software Architect"
                        });
                });

            modelBuilder.Entity("ResumePro.Entities.JobSkill", b =>
                {
                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<int>("ResumeId")
                        .HasColumnType("int");

                    b.HasKey("SkillId", "JobId");

                    b.HasIndex("ResumeId", "JobId");

                    b.HasIndex("ResumeId", "SkillId");

                    b.ToTable("JobSkill");

                    b.HasData(
                        new
                        {
                            SkillId = 1,
                            JobId = 1,
                            ResumeId = 1
                        },
                        new
                        {
                            SkillId = 1,
                            JobId = 2,
                            ResumeId = 1
                        },
                        new
                        {
                            SkillId = 9,
                            JobId = 1,
                            ResumeId = 1
                        },
                        new
                        {
                            SkillId = 18,
                            JobId = 1,
                            ResumeId = 1
                        },
                        new
                        {
                            SkillId = 19,
                            JobId = 1,
                            ResumeId = 1
                        },
                        new
                        {
                            SkillId = 20,
                            JobId = 1,
                            ResumeId = 1
                        },
                        new
                        {
                            SkillId = 21,
                            JobId = 1,
                            ResumeId = 1
                        },
                        new
                        {
                            SkillId = 22,
                            JobId = 1,
                            ResumeId = 1
                        },
                        new
                        {
                            SkillId = 7,
                            JobId = 1,
                            ResumeId = 1
                        },
                        new
                        {
                            SkillId = 23,
                            JobId = 1,
                            ResumeId = 1
                        },
                        new
                        {
                            SkillId = 24,
                            JobId = 1,
                            ResumeId = 1
                        });
                });

            modelBuilder.Entity("ResumePro.Entities.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GitHub")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkedIn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persona");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Salt Lake City",
                            Email = "rodmjay@gmail.com",
                            FirstName = "Rod",
                            GitHub = "https://www.linkedin.com/in/rodmjay",
                            LastName = "Johnson",
                            LinkedIn = "https://www.github.com/rodmjay",
                            PhoneNumber = "3853526026",
                            State = "UT"
                        });
                });

            modelBuilder.Entity("ResumePro.Entities.PersonaSkill", b =>
                {
                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("PersonaId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("PersonaSkill");

                    b.HasData(
                        new
                        {
                            PersonaId = 1,
                            SkillId = 1,
                            Rating = 10
                        },
                        new
                        {
                            PersonaId = 1,
                            SkillId = 2,
                            Rating = 9
                        },
                        new
                        {
                            PersonaId = 1,
                            SkillId = 3,
                            Rating = 9
                        },
                        new
                        {
                            PersonaId = 1,
                            SkillId = 4,
                            Rating = 9
                        },
                        new
                        {
                            PersonaId = 1,
                            SkillId = 5,
                            Rating = 10
                        },
                        new
                        {
                            PersonaId = 1,
                            SkillId = 6,
                            Rating = 8
                        },
                        new
                        {
                            PersonaId = 1,
                            SkillId = 7,
                            Rating = 9
                        },
                        new
                        {
                            PersonaId = 1,
                            SkillId = 8,
                            Rating = 8
                        },
                        new
                        {
                            PersonaId = 1,
                            SkillId = 9,
                            Rating = 8
                        },
                        new
                        {
                            PersonaId = 1,
                            SkillId = 10,
                            Rating = 8
                        },
                        new
                        {
                            PersonaId = 1,
                            SkillId = 11,
                            Rating = 8
                        },
                        new
                        {
                            PersonaId = 1,
                            SkillId = 12,
                            Rating = 8
                        },
                        new
                        {
                            PersonaId = 1,
                            SkillId = 13,
                            Rating = 8
                        },
                        new
                        {
                            PersonaId = 1,
                            SkillId = 14,
                            Rating = 8
                        },
                        new
                        {
                            PersonaId = 1,
                            SkillId = 15,
                            Rating = 8
                        },
                        new
                        {
                            PersonaId = 1,
                            SkillId = 16,
                            Rating = 8
                        },
                        new
                        {
                            PersonaId = 1,
                            SkillId = 17,
                            Rating = 8
                        },
                        new
                        {
                            PersonaId = 1,
                            SkillId = 18,
                            Rating = 8
                        },
                        new
                        {
                            PersonaId = 1,
                            SkillId = 19,
                            Rating = 8
                        },
                        new
                        {
                            PersonaId = 1,
                            SkillId = 20,
                            Rating = 8
                        },
                        new
                        {
                            PersonaId = 1,
                            SkillId = 21,
                            Rating = 8
                        },
                        new
                        {
                            PersonaId = 1,
                            SkillId = 22,
                            Rating = 8
                        },
                        new
                        {
                            PersonaId = 1,
                            SkillId = 23,
                            Rating = 8
                        },
                        new
                        {
                            PersonaId = 1,
                            SkillId = 24,
                            Rating = 8
                        });
                });

            modelBuilder.Entity("ResumePro.Entities.Reference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("Reference");
                });

            modelBuilder.Entity("ResumePro.Entities.Resume", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Resume");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Rod is an enterprise architect with expertise in the latest .NET and web technologies.  Rod has 19 years of experience as a professional developer and architect, with expertise in the complete software development lifecycle from ideation to implementation.  Rod is consistently described as a 10x developer who delivers high-end software from the ground up.",
                            PersonaId = 1,
                            ShortName = "Enterprice Application Architect"
                        });
                });

            modelBuilder.Entity("ResumePro.Entities.ResumeJob", b =>
                {
                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<int>("ResumeId")
                        .HasColumnType("int");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("PersonaId", "ResumeId", "JobId");

                    b.HasIndex("JobId");

                    b.ToTable("ResumeJob");

                    b.HasData(
                        new
                        {
                            PersonaId = 1,
                            ResumeId = 1,
                            JobId = 1,
                            Order = 0
                        },
                        new
                        {
                            PersonaId = 1,
                            ResumeId = 1,
                            JobId = 2,
                            Order = 0
                        });
                });

            modelBuilder.Entity("ResumePro.Entities.ResumeSkill", b =>
                {
                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<int>("ResumeId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<bool>("ShowInSummary")
                        .HasColumnType("bit");

                    b.HasKey("PersonaId", "ResumeId", "SkillId");

                    b.HasIndex("PersonaId", "SkillId");

                    b.ToTable("ResumeSkill");

                    b.HasData(
                        new
                        {
                            PersonaId = 1,
                            ResumeId = 1,
                            SkillId = 1,
                            ShowInSummary = true
                        },
                        new
                        {
                            PersonaId = 1,
                            ResumeId = 1,
                            SkillId = 2,
                            ShowInSummary = true
                        },
                        new
                        {
                            PersonaId = 1,
                            ResumeId = 1,
                            SkillId = 3,
                            ShowInSummary = true
                        },
                        new
                        {
                            PersonaId = 1,
                            ResumeId = 1,
                            SkillId = 4,
                            ShowInSummary = true
                        },
                        new
                        {
                            PersonaId = 1,
                            ResumeId = 1,
                            SkillId = 5,
                            ShowInSummary = true
                        },
                        new
                        {
                            PersonaId = 1,
                            ResumeId = 1,
                            SkillId = 6,
                            ShowInSummary = false
                        },
                        new
                        {
                            PersonaId = 1,
                            ResumeId = 1,
                            SkillId = 7,
                            ShowInSummary = false
                        },
                        new
                        {
                            PersonaId = 1,
                            ResumeId = 1,
                            SkillId = 8,
                            ShowInSummary = false
                        },
                        new
                        {
                            PersonaId = 1,
                            ResumeId = 1,
                            SkillId = 9,
                            ShowInSummary = false
                        },
                        new
                        {
                            PersonaId = 1,
                            ResumeId = 1,
                            SkillId = 10,
                            ShowInSummary = false
                        },
                        new
                        {
                            PersonaId = 1,
                            ResumeId = 1,
                            SkillId = 11,
                            ShowInSummary = false
                        },
                        new
                        {
                            PersonaId = 1,
                            ResumeId = 1,
                            SkillId = 12,
                            ShowInSummary = false
                        },
                        new
                        {
                            PersonaId = 1,
                            ResumeId = 1,
                            SkillId = 13,
                            ShowInSummary = false
                        },
                        new
                        {
                            PersonaId = 1,
                            ResumeId = 1,
                            SkillId = 14,
                            ShowInSummary = false
                        },
                        new
                        {
                            PersonaId = 1,
                            ResumeId = 1,
                            SkillId = 15,
                            ShowInSummary = false
                        },
                        new
                        {
                            PersonaId = 1,
                            ResumeId = 1,
                            SkillId = 16,
                            ShowInSummary = false
                        },
                        new
                        {
                            PersonaId = 1,
                            ResumeId = 1,
                            SkillId = 17,
                            ShowInSummary = false
                        },
                        new
                        {
                            PersonaId = 1,
                            ResumeId = 1,
                            SkillId = 18,
                            ShowInSummary = false
                        },
                        new
                        {
                            PersonaId = 1,
                            ResumeId = 1,
                            SkillId = 19,
                            ShowInSummary = false
                        },
                        new
                        {
                            PersonaId = 1,
                            ResumeId = 1,
                            SkillId = 20,
                            ShowInSummary = false
                        },
                        new
                        {
                            PersonaId = 1,
                            ResumeId = 1,
                            SkillId = 21,
                            ShowInSummary = false
                        },
                        new
                        {
                            PersonaId = 1,
                            ResumeId = 1,
                            SkillId = 22,
                            ShowInSummary = false
                        },
                        new
                        {
                            PersonaId = 1,
                            ResumeId = 1,
                            SkillId = 23,
                            ShowInSummary = false
                        },
                        new
                        {
                            PersonaId = 1,
                            ResumeId = 1,
                            SkillId = 24,
                            ShowInSummary = false
                        });
                });

            modelBuilder.Entity("ResumePro.Entities.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Skill");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "C# Development"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Azure"
                        },
                        new
                        {
                            Id = 3,
                            Title = "Sql Server"
                        },
                        new
                        {
                            Id = 4,
                            Title = "Angular"
                        },
                        new
                        {
                            Id = 5,
                            Title = "Entity Framework"
                        },
                        new
                        {
                            Id = 6,
                            Title = "TypeScript"
                        },
                        new
                        {
                            Id = 7,
                            Title = "CI/CD"
                        },
                        new
                        {
                            Id = 8,
                            Title = "oAuth2"
                        },
                        new
                        {
                            Id = 9,
                            Title = "Visual Studio 2022"
                        },
                        new
                        {
                            Id = 10,
                            Title = "Identity Server"
                        },
                        new
                        {
                            Id = 11,
                            Title = "Postman"
                        },
                        new
                        {
                            Id = 12,
                            Title = "SignalR"
                        },
                        new
                        {
                            Id = 13,
                            Title = "Material Design"
                        },
                        new
                        {
                            Id = 14,
                            Title = "Bootstrap"
                        },
                        new
                        {
                            Id = 15,
                            Title = "Figma"
                        },
                        new
                        {
                            Id = 16,
                            Title = "gRPC"
                        },
                        new
                        {
                            Id = 17,
                            Title = "Blazor"
                        },
                        new
                        {
                            Id = 18,
                            Title = "Geneva"
                        },
                        new
                        {
                            Id = 19,
                            Title = "Data Explorer"
                        },
                        new
                        {
                            Id = 20,
                            Title = "Synapse"
                        },
                        new
                        {
                            Id = 21,
                            Title = "Function Apps"
                        },
                        new
                        {
                            Id = 22,
                            Title = "AppInsights"
                        },
                        new
                        {
                            Id = 23,
                            Title = "Kusto"
                        },
                        new
                        {
                            Id = 24,
                            Title = "Bicep"
                        });
                });

            modelBuilder.Entity("ResumePro.Entities.Highlight", b =>
                {
                    b.HasOne("ResumePro.Entities.Job", "Job")
                        .WithMany("Highlighs")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("ResumePro.Entities.Job", b =>
                {
                    b.HasOne("ResumePro.Entities.Persona", "Persona")
                        .WithMany("Jobs")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("ResumePro.Entities.JobSkill", b =>
                {
                    b.HasOne("ResumePro.Entities.ResumeJob", "Job")
                        .WithMany("Skills")
                        .HasForeignKey("ResumeId", "JobId")
                        .HasPrincipalKey("ResumeId", "JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResumePro.Entities.ResumeSkill", "Skill")
                        .WithMany("Jobs")
                        .HasForeignKey("ResumeId", "SkillId")
                        .HasPrincipalKey("ResumeId", "SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("ResumePro.Entities.PersonaSkill", b =>
                {
                    b.HasOne("ResumePro.Entities.Persona", "Persona")
                        .WithMany("Skills")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResumePro.Entities.Skill", "Skill")
                        .WithMany("Personas")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("ResumePro.Entities.Reference", b =>
                {
                    b.HasOne("ResumePro.Entities.Job", "Job")
                        .WithMany("References")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("ResumePro.Entities.Resume", b =>
                {
                    b.HasOne("ResumePro.Entities.Persona", "Persona")
                        .WithMany("Resumes")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("ResumePro.Entities.ResumeJob", b =>
                {
                    b.HasOne("ResumePro.Entities.Job", "Job")
                        .WithMany("Resumes")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ResumePro.Entities.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResumePro.Entities.Resume", "Resume")
                        .WithMany("Jobs")
                        .HasForeignKey("PersonaId", "ResumeId")
                        .HasPrincipalKey("PersonaId", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Persona");

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("ResumePro.Entities.ResumeSkill", b =>
                {
                    b.HasOne("ResumePro.Entities.Resume", "Resume")
                        .WithMany("Skills")
                        .HasForeignKey("PersonaId", "ResumeId")
                        .HasPrincipalKey("PersonaId", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ResumePro.Entities.PersonaSkill", "Skill")
                        .WithMany("Resumes")
                        .HasForeignKey("PersonaId", "SkillId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Resume");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("ResumePro.Entities.Job", b =>
                {
                    b.Navigation("Highlighs");

                    b.Navigation("References");

                    b.Navigation("Resumes");
                });

            modelBuilder.Entity("ResumePro.Entities.Persona", b =>
                {
                    b.Navigation("Jobs");

                    b.Navigation("Resumes");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("ResumePro.Entities.PersonaSkill", b =>
                {
                    b.Navigation("Resumes");
                });

            modelBuilder.Entity("ResumePro.Entities.Resume", b =>
                {
                    b.Navigation("Jobs");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("ResumePro.Entities.ResumeJob", b =>
                {
                    b.Navigation("Skills");
                });

            modelBuilder.Entity("ResumePro.Entities.ResumeSkill", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("ResumePro.Entities.Skill", b =>
                {
                    b.Navigation("Personas");
                });
#pragma warning restore 612, 618
        }
    }
}
